version: "3"

networks:
  api_network:

services:
  api:
    build: .
    image: $API_IMAGE
    environment:
      - NODE_ENV=production
      - PORT=$PORT
      - API_NAME=$API_NAME
      - API_TOKEN=$API_TOKEN
      - API_IMAGE=$API_IMAGE
      - AWS_SES_ACCESS_KEY_ID=$AWS_SES_ACCESS_KEY_ID
      - AWS_SES_SECRET_ACCESS_KEY=$AWS_SES_SECRET_ACCESS_KEY
      - AWS_SES_REGION=$AWS_SES_REGION
      - MONGODB_PROTOCOL=$MONGODB_PROTOCOL
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_SERVER=$MONGODB_SERVER
      - MONGODB_PORT=$MONGODB_PORT
      - MONGODB_DATABASE=$MONGODB_DATABASE
    logging:
      driver: json-file
      options:
        max-size: 50m
    networks:
      - api_network
    ports:
      - $PORT:$PORT
    restart: always

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    logging:
      driver: json-file
      options:
        max-size: 50m
    networks:
      - api_network
    ports:
      - $MONGODB_PORT:27017
    restart: always
    volumes:
      - mongodb_volume:/data/db

volumes:
  mongodb_volume:
